### ISSUE TITLE
No longer able to authenticate to Google

### ISSUE THREAD

**Issue by rozzin** [ZeWaren/jabber-hangouts-transport#14]
See upstream hangups bug: https://github.com/tdryer/hangups/issues/260

**Comment by diggit** [comment]
@ZeWaren this is fixed in new hangups release 0.4.0, hangups update/using upstream is necessary

**Comment by ivucica** [comment]
FWIW I have merely applied tdryer/hangups@d845b00e50dedb5182cc87864121147563c7c8d4 from upstream and this fixed the issue.

**Comment by rozzin** [comment]
@ivucica wrote:

> FWIW I have merely applied tdryer/hangups@d845b00 from upstream and this fixed the issue.

Can you clarify what it means that you "applied tdryer/hangups@d845b00"? Just replacing the the internal "lib/hangups" with a git clone of tdryer/hangups?

**Comment by diggit** [comment]
@rozzin Nope, just applying that changeset to hangups library in this repository.
It is addition of two lines, so I just copied them to appropriate files.
I can confirm, this solution works.

**Comment by ivucica** [comment]
Looks like response by email did not go through.

Yes, the above is correct. Technically I performed `patch -p1 < savedpatch.diff`.

I did not want to replace the vendored version as I couldn't be bothered to check what other changes exist between the copies. (I personally use git submodules in cases where I would be tempted to ship a copy of the code, and I refer to a forked repo if I am making some changes.)

**Comment by rozzin** [comment]
@diggit wrote:

> @rozzin Nope, just applying that changeset to hangups library in this repository.
> It is addition of two lines, so I just copied them to appropriate files.
> I can confirm, this solution works.

OK..., but you're still using the old Google auth URL (given to the user during `registration' with the transport) that no longer works ("invalid scope from oauth2")? That's the issue that I reported here--that it's not even possible to register with the transport, because the URL that the user is told to get the initial auth token from no longer works.

The specific two-line change that you and @ivucica are referencing does not alter that at all--it's not even in a relevant part of the code; you can't even get to the point where that patch matters until you've successfully registered with the transport.

You may not have run into this issue if you registered with your transports prior to Google breaking the auth API that the hangups code was using (and that the jabber-hangouts-transport code is still programmed to use); i.e., if the token that got cached in your installations is still valid.

AFAICT, there's a much larger changeset required to make jabber-hangouts-transport work with Google's new auth API; and just folding in the changes from tdryer/hangups#260 still doesn't quite fix the issue here--because jabber-hangouts-transport still needs to be updated to ask the user for their Google password and use that with the changed back-end auth mechanism. If you just drop the new hangups code in, then registration just presents users with a different URL that actually doesn't give them a token to paste back into the registration dialog--the user actually needs to sniff the HTTP headers or browser cookie-cache to find the token, now....

(and, actually, I'm not sure _that_ even makes the transport work; I've yet to get it working like that)

**Comment by diggit** [comment]
> You may not have run into this issue if you registered with your transports prior to Google breaking the auth API that the hangups code was using (and that the jabber-hangouts-transport code is still programmed to use); i.e., if the token that got cached in your installations is still valid.

Yes, this is my case. Sorry for confuse.  It is not yet solved in hangups. You'll have to wait until they fix this issue. It looks like user password is necessary to get token directly :/

**Comment by rozzin** [comment]
> AFAICT, there's a much larger changeset required to make jabber-hangouts-transport work with Google's new auth API; and just folding in the changes from tdryer/hangups#260 still doesn't quite fix the issue here--because jabber-hangouts-transport still needs to be updated to ask the user for their Google password and use that with the changed back-end auth mechanism. If you just drop the new hangups code in, then registration just presents users with a different URL that actually doesn't give them a token to paste back into the registration dialog--the user actually needs to sniff the HTTP headers or browser cookie-cache to find the token, now....
> 
> (and, actually, I'm not sure that even makes the transport work; I've yet to get it working like that)

Yeah, looks like something changed incompatibly; when I try to register with the transport after dropping in the current hangups codebase (replacing the forked "lib/hangups" tree), I get this via stdio from the daemon:

<pre>
Stanza name:  iq
[(<class 'AttributeError'>, AttributeError("'str' object has no attribute 'get'",), <traceback object at 0x7f7bd0a1e948>)]
Stanza name:  presence
[]
</pre>

... and then the transport goes into a state of "The recipient or server understands the request but is refusing to process it because it does not meet criteria defined by the recipient or server."

Looks like that's coming out of this call in `jh_hangups.py`:

<pre>self.cookies = hangups.auth.get_auth(lambda: oauth_code, self.refresh_token_filename)</pre>

... because the interface on `hangups.auth.get_auth()` changed: instead of the last parameter being a filename, it now expects that to be a `RefreshTokenCache` instance.

**Comment by rozzin** [comment]
> the interface on `hangups.auth.get_auth()` changed: instead of the last parameter being a filename, it now expects that to be a `RefreshTokenCache` instance

OK, that's easy enough to get past by just wrapping a `RefreshTokenCache` object around the filename at the point where the call is made..., but then we still run into further problems with hangups wanting to have been fed a CredentialsPrompt object (not just a function) from which it can get an e-mail address and a password to drive password-based authentication with Google and get the auth token itself rather than have it fed in (because nobody would actually want to sniff HTTP headers as part of an IM login procedure).

If I hack hangups to just use the token I give it to get past that, then I start running into my hangups library not having some features that @ZeWaren appears to have added to his fork, e.g.:

<pre>
  File "/home/rozzin/src/jabber-hangouts-transport/jh_hangups.py", line 265, in on_connect
    self.user_list.on_presence.add_observer(self.on_presence)
AttributeError: 'UserList' object has no attribute 'on_presence'
</pre>

Need to allocate some time to see if those additions are actually straightforward to pull out and rebase on top of the new upstream....

**Comment by ivucica** [comment]
No. I did patch -p1 downloadedpatch.diff. I could not be bothered to check what else would outright replacing the vendored copy do.

**Comment by niektoniekde** [comment]
Hi there.

I wanted to switch from spectrum/xmpp gateway today to this transport based on hangups lib. For me there is no problem with obtaining token from cookie as long as it works. But it doesn't.

I'm getting this error every time I paste token to prompt:
```
hangups      info   Authenticating with refresh token
root         error  
Traceback (most recent call last):
  File "__main__.py", line 136, in <module>
    connection.Process(0.01)
  File "./lib/xmpp/xmpp/dispatcher.py", line 127, in Process
    raise _pendingException[0]
AttributeError
```
I guess it's because that missing object wrap around filename which I'm not able to do by myself with current level of my Python knowledge. Could you please provide some patch or instructions what to change (how to wrap that object) as a temporary workaround?

Thanks.

**Comment by codeofdusk** [comment]
Has any more progress been made to address this issue? Is there a functional Hangouts to XMPP transport of any kind I can setup? Thanks!

**Comment by woffs** [comment]
I had managed to merge it with a newer version of hangups and it started at least. Never tested it because the last hangouts user went away from hangouts.

**Comment by rozzin** [comment]
On 03/21/2017 09:39 AM, Frank Doepper wrote:
> > Has any more progress been made to address this issue?
> > Is there a functional Hangouts to XMPP transport of any kind I can setup? Thanks!
>
> I had managed to merge it with a newer version of hangups and it started at least. Never tested it because the last
> hangouts user went away from hangouts.

Basically no, it doesn't actually work.


The authentication mechanism is sufficiently different
that there's a fair amount of work required to rework
the jabber-hangouts transport. If we want something
that's actually usable, then we need to actually ask
the XMPP transport user for their Google password,
and users of these transport servers need to give
the transports their Google passwords (or, alternately,
require users of the transport to sniff HTTP headers
to find their auth tokens).

I spent a few hours trying to hack this out myself
when the auth changes went in upstream in Hangups,
but didn't really feel like I was getting anywhere.

And at the same time Google has also  stated explicitly
that they're actively trying to make the mechanism that
the newer Hangouts code is using *not work*
(see the conversation on the ticket in Hangups)...

Though that was before Google went on to say that they
were actually in the process of just killing off Hangouts,
so who knows. The whole thing just feels like one big dead end.
